apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "simple-iot.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: iot-web
          image: {{ include "simple-iot.image" (dict "image" .Values.web.image "registry" .Values.global.imageRegistry) }}
          ports:
            - containerPort: {{ .Values.web.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.web.port }}
