CREATE TABLE tb_user (
    id integer PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    account_non_expired boolean NOT NULL DEFAULT true,
    account_non_locked boolean NOT NULL DEFAULT true,
    credentials_non_expired boolean NOT NULL DEFAULT true
);

CREATE TABLE sms_config (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    supplier varchar(50) NOT NULL,
    access_key varchar(200) NOT NULL,
    secret_key varchar(200) NOT NULL,
    sign_name varchar(100),
    template_id varchar(100),
    endpoint varchar(200),
    region varchar(50),
    config_json text,
    is_default boolean NOT NULL DEFAULT false,
    status integer NOT NULL DEFAULT 1,
    create_time timestamp,
    update_time timestamp
);

CREATE TABLE tb_iot_driver (
    driver_id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    type varchar(50) NOT NULL,
    description varchar(255),
    connection_type varchar(50),
    jar_path varchar(255),
    is_default boolean NOT NULL DEFAULT false,
    status integer NOT NULL DEFAULT 1,
    port integer NOT NULL
);

CREATE TABLE tb_protocol (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    proto_type smallint NOT NULL DEFAULT 2,
    url varchar(255) NOT NULL DEFAULT '',
    mark varchar(255) NOT NULL DEFAULT '',
    proto_key varchar(50) NOT NULL,
    handler_class varchar(255),
    script_content text,
    script_lang varchar(50),
    status integer NOT NULL DEFAULT 1
);

INSERT INTO tb_iot_driver (driver_id, name, type, description, connection_type, jar_path, is_default, status, port)
VALUES (1, 'Integration TCP Driver', 'TCP', 'Integration test driver', 'DEFAULT', NULL, false, 1, 1677);

INSERT INTO tb_protocol (name, proto_type, url, mark, proto_key, handler_class, script_content, script_lang, status)
VALUES ('System Protocol', 2, '', 'Integration test protocol', 'system-default', 'com.github.dingdaoyi.iot.proto.defaul.DefaultProtocolDecoder', NULL, NULL, 1);

CREATE TABLE tb_product_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) NOT NULL,
    parent_id integer,
    "status" integer,
    icon_url varchar(255),
    mark varchar(255),
    part_type_code varchar(50)
);

CREATE TABLE tb_product (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model varchar(100),
    manufacturer varchar(100),
    remark varchar(255),
    protocol_id integer,
    product_type_id integer,
    product_key varchar(50),
    icon varchar(255)
);

CREATE TABLE tb_device (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer,
    device_name varchar(100),
    device_key varchar(50),
    device_secret varchar(100),
    online boolean,
    active_status boolean,
    third_device_id varchar(100),
    create_time timestamp,
    update_time timestamp
);

CREATE TABLE tb_icon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    path varchar(255)
);

CREATE TABLE tb_model_property (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer,
    product_type_id integer,
    identifier varchar(50),
    "name" varchar(100),
    icon_id integer,
    data_type integer,
    access_mode varchar(10),
    param_type integer,
    custom boolean,
    parent_id integer,
    remark varchar(255),
    unit varchar(20),
    unit_name varchar(50),
    max bigint,
    min bigint,
    step bigint,
    bool0 varchar(20),
    bool1 varchar(20),
    "length" integer,
    enums text DEFAULT '[]'
);

CREATE TABLE tb_model_service (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    async boolean,
    event_type integer,
    service_type integer,
    identifier varchar(255),
    name varchar(255),
    remark varchar(255),
    product_type_id integer,
    icon_id integer,
    custom boolean,
    required boolean,
    product_id integer
);

CREATE TABLE tb_service_property (
    service_id integer,
    property_id integer,
    param_type integer
);

CREATE TABLE tb_rule_chain (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    description varchar(255),
    is_root boolean,
    is_enabled boolean,
    source_type varchar(20),
    source_id integer,
    configuration text,
    create_time timestamp,
    update_time timestamp
);

CREATE TABLE tb_alarm (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_type varchar(100),
    alarm_name varchar(100),
    severity varchar(20),
    status varchar(20),
    message text,
    device_id integer,
    device_key varchar(50),
    device_name varchar(100),
    rule_chain_id integer,
    details text,
    start_ts timestamp,
    end_ts timestamp,
    clear_ts timestamp,
    clear_by varchar(50),
    create_time timestamp,
    update_time timestamp
);

CREATE TABLE tb_device_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id integer NOT NULL DEFAULT -1,
    name varchar(100) NOT NULL,
    description varchar(500),
    create_time timestamp NOT NULL DEFAULT now(),
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE tb_device_tag (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    color varchar(20) DEFAULT '#6366f1',
    create_time timestamp NOT NULL DEFAULT now(),
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE tb_device_group_relation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id integer NOT NULL,
    group_id integer NOT NULL,
    create_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE tb_device_tag_relation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id integer NOT NULL,
    tag_id integer NOT NULL,
    create_time timestamp NOT NULL DEFAULT now()
);
